// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrC4PFwUu5lh5zPkyI3KdOq8xWia9yjs',
    appId: '1:768989006511:web:1ee10fdefe1880410ba25a',
    messagingSenderId: '768989006511',
    projectId: 'task-route-90fd2',
    authDomain: 'task-route-90fd2.firebaseapp.com',
    storageBucket: 'task-route-90fd2.appspot.com',
    measurementId: 'G-5VK6H6DKBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4yHbTIW53hyor0ST4dAqzQpE3hdPnL9w',
    appId: '1:768989006511:android:44acc051a03340ec0ba25a',
    messagingSenderId: '768989006511',
    projectId: 'task-route-90fd2',
    storageBucket: 'task-route-90fd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ddwuR-2d6UhTQQ5aKdZ39v5jm4TYVxE',
    appId: '1:768989006511:ios:d4e7f9e7c1d25c370ba25a',
    messagingSenderId: '768989006511',
    projectId: 'task-route-90fd2',
    storageBucket: 'task-route-90fd2.appspot.com',
    iosBundleId: 'com.example.flutterTask',
  );
}
